import csv
import traceback
import time
from collections import defaultdict
from datetime import datetime
from html import escape
from pathlib import Path
from typing import Any

from src.common.config import get_settings
from src.common.logger import get_logger
from src.common.models import TicketRecord
from src.common.run_context import get_run_id, start_run
from src.common.system import kill_processes
from src.excel_builder.builder import AP15Builder
from src.hda_web.client import HDAClient
from src.hda_web.ticket_parser import extract_ticket_data
from src.mailer.client import SMTPMailClient
from src.processing.logic import apply_business_rules, validate_ticket_data
from src.sap.client import SAPGuiClient


def _write_human_summary(
    output_dir: str,
    run_id: str,
    started_at: datetime,
    ended_at: datetime,
    one_time_checks: list[TicketRecord],
    valid_results: list[dict[str, Any]],
    invalid_results: list[dict[str, Any]],
    generated_csvs: list[str],
) -> str:
    """Writes a human-readable summary of the process results after all stages (HDA + SAP)."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    summary_timestamp = started_at.strftime("%Y%m%d_%H%M%S")
    summary_path = output_path / f"log_summary_{summary_timestamp}.txt"

    lines: list[str] = []
    lines.append("Daily Process Log Summary")
    lines.append("=" * 30)
    lines.append(f"Run ID: {run_id}")
    lines.append(f"Started: {started_at.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Finished: {ended_at.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Duration: {ended_at - started_at}")
    lines.append("")
    lines.append(f"1. Total OneTime Check detected in HDA Grid: {len(one_time_checks)}")
    lines.append(f"2. Passed HDA Local Validation: {len(valid_results) + len([r for r in invalid_results if 'Suspended by SAP' in str(r.get('errors', []))])}")
    lines.append(f"3. Passed SAP Final Validation: {len(valid_results)}")
    lines.append("")
    lines.append(f"FINAL RESULT: {len(valid_results)} tickets ready to pay, {len(invalid_results)} tickets suspended.")
    lines.append("")

    lines.append("--- ONE-TIME CHECK TICKETS DETECTED ---")
    if one_time_checks:
        for index, ticket in enumerate(one_time_checks, start=1):
            lines.append(
                f"{index}. {ticket.ticket_id} | company={ticket.company} | "
                f"payment_method={ticket.payment_method} | subject={ticket.subject}"
            )
    else:
        lines.append("None")
    lines.append("")

    lines.append("--- FINAL VALID TICKETS (Passed SAP Validation) ---")
    if valid_results:
        for result in valid_results:
            ticket = result["ticket"]
            proc = result["processed_data"]
            lines.append(f"- {ticket.ticket_id} | subject={ticket.subject} | company={ticket.company}")
            lines.append(f"  Amount: {proc.get('Amount')} {proc.get('Currency')} | Invoice: {proc.get('InvoiceNum')}")
            lines.append("")
    else:
        lines.append("None")
        lines.append("")

    lines.append("--- INVALID OR SUSPENDED TICKETS (Local or SAP) ---")
    if invalid_results:
        for result in invalid_results:
            ticket = result["ticket"]
            errors = result.get("errors", [])
            lines.append(f"- {ticket.ticket_id} | subject={ticket.subject} | company={ticket.company}")
            lines.append("  Reasons for suspension:")
            for error in errors:
                error_lines = str(error).splitlines()
                if error_lines:
                    lines.append(f"    * {error_lines[0]}")
                    for subline in error_lines[1:]:
                        lines.append(f"      {subline}")
            lines.append("")
    else:
        lines.append("None")
        lines.append("")

    lines.append("--- GENERATED FINAL CSV FILES ---")
    if generated_csvs:
        for csv_path in generated_csvs:
            lines.append(f"- {Path(csv_path).name}")
    else:
        lines.append("None")

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return str(summary_path)


def _get_run_output_dir(base_output_dir: str, started_at: datetime) -> Path:
    return Path(base_output_dir) / started_at.strftime("%Y%m%d")


def _build_typed_email_subject(settings: Any, started_at: datetime, mail_type: str) -> str:
    prefix = settings.mail_subject_prefix.strip()
    base_subject = f"HDA {mail_type} - {started_at.strftime('%Y-%m-%d')}"
    return f"{prefix} {base_subject}".strip() if prefix else base_subject


def _build_group_email_body(run_id: str, started_at: datetime, mail_group: str, attachments: list[str]) -> str:
    file_names = [Path(attachment).name for attachment in attachments]
    lines = [
        "Hello,", "",
        f"Attached are the HDA AP15 {mail_group} file(s) generated by the automation.", "",
        f"Run ID: {run_id}",
        f"Started: {started_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"{mail_group} CSV files attached: {len(attachments)}", "",
        "Attached files:"
    ]
    for file_name in file_names:
        lines.append(f"- {file_name}")
    return "\n".join(lines)


def _build_summary_email_body(summary_text: str, run_id: str, started_at: datetime) -> str:
    return "\n".join([
        "Hello,", "", "Below is the daily HDA automation summary.", "",
        f"Run ID: {run_id}", f"Started: {started_at.strftime('%Y-%m-%d %H:%M:%S')}", "",
        summary_text
    ])


def _build_summary_email_html(run_id: str, started_at: datetime, ended_at: datetime, one_time_checks: list[TicketRecord], valid_results: list[dict[str, Any]], invalid_results: list[dict[str, Any]], generated_csvs: list[str]) -> str:
    duration = ended_at - started_at

    def render_ticket_rows(results: list[dict[str, Any]], include_errors: bool) -> str:
        if not results:
            return "<tr><td colspan='4' style='padding:12px;border:1px solid #d9dee8;color:#5b6472;'>No tickets in this section.</td></tr>"
        rows: list[str] = []
        for result in results:
            ticket = result["ticket"]
            processed = result.get("processed_data", {})
            errors = result.get("errors", [])
            detail_lines = [
                f"Company: {ticket.company or 'N/A'}",
                f"Subject: {ticket.subject or 'N/A'}",
                f"Invoice: {processed.get('InvoiceNum', 'N/A')}",
                f"Amount: {processed.get('Amount', 'N/A')} {processed.get('Currency', '')}".strip(),
                f"Vendor: {processed.get('VendorNum', 'N/A')}",
                f"GL: {processed.get('GLAccount', 'N/A')}",
            ]
            if include_errors and errors:
                err_text = "<br>".join(escape(str(error)).replace("\n", "<br>") for error in errors)
                detail_lines.append(f"Errors: {err_text}")
            details = "<br>".join(detail_lines)
            rows.append(f"<tr><td style='padding:12px;border:1px solid #d9dee8;vertical-align:top;'>{escape(ticket.ticket_id)}</td><td style='padding:12px;border:1px solid #d9dee8;vertical-align:top;'>{escape(ticket.company or 'N/A')}</td><td style='padding:12px;border:1px solid #d9dee8;vertical-align:top;'>{escape(ticket.subject or 'N/A')}</td><td style='padding:12px;border:1px solid #d9dee8;vertical-align:top;'>{details}</td></tr>")
        return "".join(rows)

    metrics = [
        ("Run ID", run_id), ("Started", started_at.strftime("%Y-%m-%d %H:%M:%S")), ("Finished", ended_at.strftime("%Y-%m-%d %H:%M:%S")),
        ("Duration", str(duration)), ("OneTime Check tickets", str(len(one_time_checks))), ("Valid tickets", str(len(valid_results))),
        ("Invalid tickets", str(len(invalid_results))), ("CSV files generated", str(len(generated_csvs))),
    ]
    metric_cards = "".join(f"<div style='display:inline-block;width:220px;margin:0 12px 12px 0;padding:14px 16px;background:#f5f7fb;border:1px solid #d9dee8;border-radius:10px;vertical-align:top;'><div style='font-size:12px;color:#5b6472;text-transform:uppercase;letter-spacing:.04em;'>{escape(label)}</div><div style='margin-top:6px;font-size:18px;font-weight:700;color:#122033;'>{escape(value)}</div></div>" for label, value in metrics)
    one_time_items = [f"{ticket.ticket_id} | {ticket.company} | {ticket.subject}" for ticket in one_time_checks]
    csv_items = [Path(csv_path).name for csv_path in generated_csvs]

    return f"""<html><body style="margin:0;padding:24px;background:#eef3f8;font-family:Segoe UI,Arial,sans-serif;color:#122033;"><div style="max-width:960px;margin:0 auto;background:#ffffff;border:1px solid #d9dee8;border-radius:16px;overflow:hidden;"><div style="padding:24px 28px;background:#183153;color:#ffffff;"><div style="font-size:13px;letter-spacing:.08em;text-transform:uppercase;opacity:.85;">HDA Automation</div><h1 style="margin:10px 0 0;font-size:28px;line-height:1.2;">Daily Summary</h1></div><div style="padding:28px;"><h2 style="margin:0 0 16px;font-size:18px;color:#122033;">Overview</h2><div>{metric_cards}</div><h2 style="margin:24px 0 12px;font-size:18px;color:#122033;">Valid Tickets</h2><table style="width:100%;border-collapse:collapse;font-size:14px;"><thead><tr style="background:#f5f7fb;"><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Ticket</th><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Company</th><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Subject</th><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Details</th></tr></thead><tbody>{render_ticket_rows(valid_results, False)}</tbody></table><h2 style="margin:24px 0 12px;font-size:18px;color:#122033;">Invalid Tickets</h2><table style="width:100%;border-collapse:collapse;font-size:14px;"><thead><tr style="background:#fff4f2;"><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Ticket</th><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Company</th><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Subject</th><th style="padding:12px;border:1px solid #d9dee8;text-align:left;">Details</th></tr></thead><tbody>{render_ticket_rows(invalid_results, True)}</tbody></table></div></div></body></html>"""


def _build_error_email_body(run_id: str, started_at: datetime, current_stage: str, exc: Exception, log_path: str) -> str:
    return "\n".join([
        "Hello,", "", "The HDA automation failed.", "",
        f"Run ID: {run_id}", f"Started: {started_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Failed during: {current_stage}", f"Exception type: {type(exc).__name__}",
        f"Error message: {exc}", f"Technical log: {log_path}", "",
        "Please review the attached technical log for more details.", "",
        "Traceback:", traceback.format_exc()
    ])


def _get_log_path(settings: Any, run_id: str) -> str:
    return str(Path(settings.log_dir) / f"{run_id}.log")


def _get_mail_group_from_csv_path(csv_path: str) -> str | None:
    csv_name = Path(csv_path).name.upper()
    if "_FMS_" in csv_name: return "FMS"
    if "_AFS_" in csv_name: return "AFS"
    return None


def _group_csvs_by_mail_group(generated_csvs: list[str]) -> dict[str, list[str]]:
    grouped = {"FMS": [], "AFS": []}
    for csv_path in generated_csvs:
        mail_group = _get_mail_group_from_csv_path(csv_path)
        if mail_group: grouped[mail_group].append(csv_path)
    return grouped


def _collect_invoice_numbers_from_csv(csv_path: str) -> list[str]:
    csv_file_path = Path(csv_path)
    if not csv_file_path.exists(): return []
    try:
        with csv_file_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
            reader = csv.DictReader(csv_file)
            return [str(row.get("Invoice Number", "")).strip() for row in reader if str(row.get("Invoice Number", "")).strip()]
    except Exception: return []


def _resolve_mail_recipients(settings: Any, mail_type: str) -> list[str]:
    recipient_by_type = {
        "FMS": settings.mail_fms_recipient or settings.mail_usd_recipient,
        "AFS": settings.mail_afs_recipient or settings.mail_cad_recipient,
        "SUMMARY": settings.mail_summary_recipient,
        "ERROR": settings.mail_error_recipient,
    }
    preferred = settings.mail_test_recipient or recipient_by_type.get(mail_type, "")
    if not preferred: preferred = ",".join(filter(None, [settings.mail_primary_recipient, settings.mail_secondary_recipient]))
    return [r.strip() for r in preferred.replace(";", ",").split(",") if r.strip()]


def _collect_one_time_checks_with_retry(client: HDAClient, logger: Any, abort_event: Any = None, attempts: int = 3) -> tuple[list[TicketRecord], list[TicketRecord]]:
    last_tickets, one_time_checks = [], []
    for attempt in range(1, attempts + 1):
        if abort_event and abort_event.is_set(): break
        if attempt > 1:
            logger.warning(f"Retry {attempt-1}/{attempts} for OneTime Check tickets...")
            try: client.click_payments_tile()
            except Exception: pass
            time.sleep(4)
        tickets = client.read_payment_grid_rows()
        last_tickets = tickets
        one_time_checks = [t for t in tickets if "onetime check" in t.payment_method.replace('\xa0', ' ').strip().lower() and t.status.replace('\xa0', ' ').strip().lower() == "open"]
        logger.info(f"Attempt {attempt}/{attempts} | Total: {len(tickets)} | Candidates: {len(one_time_checks)}")
        if one_time_checks: break
    return last_tickets, one_time_checks

import threading

def process_all_tickets(abort_event: threading.Event = None) -> None:
    if abort_event and abort_event.is_set(): return
    start_run("process_all_tickets")
    logger, settings, client = get_logger("process_all_tickets"), get_settings(), HDAClient()
    mail_client, run_id, started_at = SMTPMailClient(settings), get_run_id(), datetime.now()
    run_output_dir = _get_run_output_dir(settings.output_dir, started_at)
    log_path, builder = _get_log_path(settings, run_id), AP15Builder(str(run_output_dir))
    
    valid_tickets, invalid_tickets, generated_csvs, one_time_checks, summary_path = [], [], [], [], None
    current_stage = "initialization"

    try:
        logger.info("Cleaning up processes...")
        kill_processes(["msedge.exe", "msedgedriver.exe", "saplogon.exe", "sapgui.exe"])
        time.sleep(2)
        
        current_stage = "login and navigation"
        client.start()
        client.login()
        client.click_payments_tile()

        current_stage = "grid extraction"
        _, one_time_checks = _collect_one_time_checks_with_retry(client, logger, abort_event)
        
        if not one_time_checks:
            logger.warning("No tickets found. Proceeding to empty summary.")
        else:
            for i, ticket in enumerate(one_time_checks, start=1):
                if abort_event and abort_event.is_set(): break
                current_stage = f"processing {ticket.ticket_id}"
                try:
                    client.open_ticket_by_id(ticket.ticket_id)
                    raw = extract_ticket_data(client.driver)
                    raw.update({"Id": ticket.ticket_id, "Created": ticket.created or "Empty"})
                    processed = apply_business_rules(raw)
                    errors = validate_ticket_data(processed)
                    if errors:
                        invalid_tickets.append({"ticket": ticket, "raw_data": raw, "processed_data": processed, "errors": errors})
                    else:
                        valid_tickets.append({"ticket": ticket, "raw_data": raw, "processed_data": processed})
                except Exception as e:
                    logger.error(f"Error ticket {ticket.ticket_id}: {e}")
                    invalid_tickets.append({"ticket": ticket, "errors": [str(e)]})
                finally: client.close_active_ticket_tab()

            if valid_tickets:
                current_stage = "SAP validation"
                candidate_csvs = builder.build([vt["processed_data"] for vt in valid_tickets], file_suffix=run_id)
                final_csvs_by_group, sap_suspended = defaultdict(list), set()
                sap_reasons = {}

                for csv_path in candidate_csvs:
                    if abort_event and abort_event.is_set(): break
                    m_group = _get_mail_group_from_csv_path(csv_path) or "GRP"
                    parts = Path(csv_path).name.split("_")
                    vendor, currency = (parts[2], parts[3]) if len(parts) >= 4 else ("UNK", "UNK")
                    sap = SAPGuiClient(settings)
                    try:
                        res = sap.validate_csv_until_clean(csv_path, retry_suffix=f"{m_group}_{vendor}")
                        sap_suspended.update(res.get("all_suspended_invoices", []))
                        sap_reasons.update(res.get("suspension_reasons", {}))
                        if res["status"] == "clean":
                            _, rows = sap._read_csv_rows(res["final_csv_path"])
                            if rows: final_csvs_by_group[(m_group, currency)].append(res["final_csv_path"])
                    finally: sap.close()

                if sap_suspended:
                    still_valid = []
                    for entry in valid_tickets:
                        inv = entry["processed_data"]["InvoiceNum"]
                        if inv in sap_suspended:
                            entry["errors"] = [f"SAP: {r}" for r in sap_reasons.get(inv, [])]
                            invalid_tickets.append(entry)
                        else: still_valid.append(entry)
                    valid_tickets = still_valid

                for (grp, curr), paths in final_csvs_by_group.items():
                    generated_csvs.append(builder.merge_csvs(paths, f"AP15_{grp}_FINAL_{started_at.strftime('%y%m%d')}_{curr}"))

        if invalid_tickets:
            for item in invalid_tickets:
                try:
                    client.open_ticket_by_id(item["ticket"].ticket_id)
                    client.update_ticket_status_ui(item["ticket"].ticket_id, "Suspend", item.get("errors"))
                finally: client.close_active_ticket_tab()

        if valid_tickets:
            for item in valid_tickets:
                try:
                    client.open_ticket_by_id(item["ticket"].ticket_id)
                    client.update_ticket_status_ui(item["ticket"].ticket_id, "In Progress")
                finally: client.close_active_ticket_tab()

        current_stage = "reporting"
        summary_path = _write_human_summary(str(run_output_dir), run_id, started_at, datetime.now(), one_time_checks, valid_tickets, invalid_tickets, generated_csvs)
        _send_final_reports(settings, mail_client, logger, run_id, started_at, run_output_dir, one_time_checks, valid_tickets, invalid_tickets, generated_csvs, summary_path)
    except Exception as exc:
        logger.exception(f"Fatal error: {exc}")
        _send_error_email(settings, mail_client, logger, run_id, started_at, current_stage, exc, log_path)
    finally: client.close()


def _send_final_reports(settings, mail_client, logger, run_id, started_at, run_output_dir, one_time_checks, valid_tickets, invalid_tickets, generated_csvs, summary_path):
    if not summary_path:
        summary_path = _write_human_summary(str(run_output_dir), run_id, started_at, datetime.now(), one_time_checks, valid_tickets, invalid_tickets, generated_csvs)
    
    if not settings.smtp_host: return

    mail_groups = _group_csvs_by_mail_group(generated_csvs)
    for group, csvs in mail_groups.items():
        if csvs:
            try:
                mail_client.send_message(
                    subject=_build_typed_email_subject(settings, started_at, f"AP15 {group}"),
                    body=_build_group_email_body(run_id, started_at, group, csvs),
                    attachments=csvs, recipients=_resolve_mail_recipients(settings, group)
                )
            except Exception as e: logger.error(f"Group email failed: {e}")

    try:
        text = Path(summary_path).read_text(encoding="utf-8")
        mail_client.send_message(
            subject=_build_typed_email_subject(settings, started_at, "Automation Summary"),
            body=_build_summary_email_body(text, run_id, started_at),
            html_body=_build_summary_email_html(run_id, started_at, datetime.now(), one_time_checks, valid_tickets, invalid_tickets, generated_csvs),
            attachments=[], recipients=_resolve_mail_recipients(settings, "SUMMARY")
        )
    except Exception as e: logger.error(f"Summary email failed: {e}")


def _send_error_email(settings, mail_client, logger, run_id, started_at, stage, exc, log_path):
    try:
        recipients = list(set(_resolve_mail_recipients(settings, "ERROR") + _resolve_mail_recipients(settings, "SUMMARY")))
        mail_client.send_message(
            subject=_build_typed_email_subject(settings, started_at, "Automation FAILED"),
            body=_build_error_email_body(run_id, started_at, stage, exc, log_path),
            attachments=[log_path], recipients=recipients
        )
    except Exception as e: logger.error(f"Error email failed: {e}")

if __name__ == "__main__":
    process_all_tickets()
